return {
  'pmizio/typescript-tools.nvim',
  ft = { 'typescript', 'typescriptreact', 'javascript', 'javascriptreact' },
  dependencies = { 'nvim-lua/plenary.nvim', 'neovim/nvim-lspconfig' },
  opts = {
    expose_as_code_action = 'all',
    complete_function_calls = false,
    jsx_close_tag = {
      enable = true,
      filetypes = { 'javascriptreact', 'typescriptreact' },
    },
    tsserver_file_preferences = {
      includeInlayParameterNameHints = 'all',
      includeInlayVariableTypeHints = true,
      includeInlayFunctionLikeReturnTypeHints = true,
      includeInlayPropertyDeclarationTypeHints = true,
      includeCompletionsForModuleExports = true,
      includeCompletionsWithInsertText = true,
      importModuleSpecifierPreference = 'non-relative',
      quotePreference = 'auto',
    },
    tsserver_format_options = {
      insertSpaceAfterCommaDelimiter = true,
      insertSpaceAfterFunctionKeywordForAnonymousFunctions = true,
      insertSpaceBeforeAndAfterBinaryOperators = true,
      insertSpaceAfterKeywordsInControlFlowStatements = true,
      semicolons = 'insert',
      quotePreference = 'single',
      indentSize = 2,
      tabSize = 2,
      convertTabsToSpaces = true,
    },
  },
  keys = {
    { 'gto', '<cmd>TSToolsOrganizeImports<cr>', desc = 'Sort Imports' },
    { 'gti', '<cmd>TSToolsAddMissingImports<cr>', desc = 'Add Missing Imports' },
    { 'gta', '<cmd>TSToolsFixAll<cr>', desc = 'Fix Missing Errors' },
    { 'gts', '<cmd>TSToolsRemoveUnused<cr>', desc = 'Remove Unused Statements' },
    { 'gtr', '<cmd>TSToolsRenameFile<cr>', desc = 'File Rename Global' },
  },
}
